apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-service-a-to-service-b
spec:
  podSelector:
    matchLabels:
      app: service-a
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchExpressions:
        - key: app
          operator: NotIn     
          values: ["service-b"]