apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-role
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]